module.exports = {
    "data": [
        {
            "id": 129506,
            "catetypeid": 32,
            "lat": 31.114828,
            "lng": 121.066193,
            "score": 4,
            "image": "https://pic.qyer.com/album/user/863/21/SU9WQBsFYQ/index/",
            "cn_name": "朱家角",
            "average_hours": "1小时",
            "percentage": 10,
            "comment": "优哉游哉朱家角&尚都里看了一整天的雨，在小小的江南古镇里。打着透明的伞一步步走在微滑的石板路上，驱走大半年的紧绷与疲惫，放空自己......",
            "user_id": 9852411,
            "user_name": "Gidget",
            "avatar": "https://pic.qyer.com/avatar/009/85/24/11/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 129501,
            "catetypeid": 32,
            "lat": 31.240891,
            "lng": 121.490189,
            "score": 4,
            "image": "https://pic.qyer.com/album/user/1831/1/QEFWQxoGZ0s/index/",
            "cn_name": "外滩",
            "average_hours": "1小时",
            "percentage": 61,
            "comment": "人多，但是不影响观看和感受，夜晚肯定很美可惜没等到夜晚，川流不息的人群，我觉得也是外滩的风景之一",
            "user_id": 1959997,
            "user_name": "vivian5058",
            "avatar": "https://pic.qyer.com/avatar/001/95/99/97/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 129539,
            "catetypeid": 32,
            "lat": 31.032642,
            "lng": 121.228928,
            "score": 3,
            "image": "https://pic.qyer.com/album/user/863/20/SU9WQBoAaA/index/",
            "cn_name": "松江",
            "average_hours": "1小时",
            "percentage": 8,
            "comment": "松江区？这么大，啥时候能逛完呀，建议换个地方",
            "user_id": 10395441,
            "user_name": "常胜小子龙",
            "avatar": "https://pic.qyer.com/avatar/010/39/54/41/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 129505,
            "catetypeid": 32,
            "lat": 31.240768,
            "lng": 121.481796,
            "score": 4,
            "image": "https://pic.qyer.com/album/168/58/145071/index/",
            "cn_name": "南京路",
            "average_hours": "1小时",
            "percentage": 22,
            "comment": "太挤了。。。。。。。。。。。。",
            "user_id": 1202028,
            "user_name": "youyuguitar",
            "avatar": "https://pic.qyer.com/avatar/001/20/20/28/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 129500,
            "catetypeid": 32,
            "lat": 31.239689,
            "lng": 121.499756,
            "score": 4,
            "image": "https://pic.qyer.com/album/user/863/19/SU9WQxMDYQ/index/",
            "cn_name": "东方明珠电视塔",
            "average_hours": "1小时",
            "percentage": 46,
            "comment": "里面有个玻璃长廊，墙壁都是用玻璃做的，但这个得做一个电梯，最好晚上去。",
            "user_id": 10993235,
            "user_name": "变了变了终于变了",
            "avatar": "https://pic.qyer.com/avatar/010/99/32/35/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 129568,
            "catetypeid": 32,
            "lat": 30.917883,
            "lng": 121.474075,
            "image": "https://pic.qyer.com/album/user/863/19/SU9WQxMCYw/index/",
            "cn_name": "奉贤",
            "average_hours": "1小时",
            "percentage": 1,
            "isrecommend": false,
            "en_name": "",
            "score": [],
            "user_id": 0,
            "user_name": "",
            "avatar": "",
            "comment": "",
            "lm": ""
        },
        {
            "id": 129502,
            "catetypeid": 32,
            "lat": 31.208599,
            "lng": 121.468781,
            "score": 3,
            "image": "https://pic.qyer.com/album/user/1767/39/QE5TRRkOZE0/index/",
            "cn_name": "田子坊",
            "average_hours": "1小时",
            "percentage": 43,
            "comment": "什么意思都没有  倒是爱上了全家超市",
            "user_id": 11904171,
            "user_name": "丞丞和潞潞",
            "avatar": "https://pic.qyer.com/avatar/011/90/41/71/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 129511,
            "catetypeid": 32,
            "lat": 31.222065,
            "lng": 121.537994,
            "score": 4,
            "image": "https://pic.qyer.com/album/user/863/20/SU9WQBoBaA/index/",
            "cn_name": "上海科技馆",
            "average_hours": "1小时",
            "percentage": 5,
            "comment": "适合亲子游，上海学生应该都去过",
            "user_id": 7515357,
            "user_name": "常棣",
            "avatar": "https://pic.qyer.com/avatar/007/51/53/57/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 1456738,
            "catetypeid": 32,
            "lat": 31.240261,
            "lng": 121.490578,
            "score": 5,
            "image": "https://pic.qyer.com/album/user/3098/35/QklcShkCZ0E/index/",
            "cn_name": "上海外滩",
            "average_hours": "1小时",
            "percentage": 0,
            "comment": "除了人多，什么都好~~高楼大厦林立，各种风格的建筑，吃饭购物一应俱全~",
            "user_id": 4923060,
            "user_name": "柑橘立夏",
            "avatar": "https://pic.qyer.com/avatar/004/92/30/60/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 1456802,
            "catetypeid": 32,
            "lat": 31.239689,
            "lng": 121.499756,
            "score": 5,
            "image": "https://pic.qyer.com/album/user/3302/79/QkpVQB0OY04/index/",
            "cn_name": "东方明珠",
            "average_hours": "1小时",
            "percentage": 0,
            "comment": "屹立在黄浦江畔的东方明珠电视塔可以说是上海这座城市的象征了，现在交通方便很多，周末就可以来玩，去的时候坐的地铁，2号线陆家嘴站下，出站过了马路就到了东方明珠塔底了。真的可以用人山人海来形容了，排队买票花时间很长，建议在网上购好票。登顶看风景的感觉还是不错的。",
            "user_id": 4989797,
            "user_name": "DrZou92",
            "avatar": "https://pic.qyer.com/avatar/004/98/97/97/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 1456801,
            "catetypeid": 32,
            "lat": 31.23472,
            "lng": 121.474899,
            "score": 4,
            "image": "https://pic.qyer.com/album/user/3035/37/QklWRxkAZEA/index/",
            "cn_name": "南京路步行街",
            "average_hours": "1小时",
            "percentage": 0,
            "comment": "来这里就是为了逛这家店，虽不限流但是人也不少，周边东西不便宜，一面墙的五颜六色的豆子，颜色鲜艳，不买点就离开会觉得过意不去的",
            "user_id": 1959997,
            "user_name": "vivian5058",
            "avatar": "https://pic.qyer.com/avatar/001/95/99/97/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 1456741,
            "catetypeid": 32,
            "lat": 31.225719,
            "lng": 121.492592,
            "score": 5,
            "image": "https://pic.qyer.com/album/user/3338/88/QkpWShIPaU8/index/",
            "cn_name": "上海城隍庙",
            "average_hours": "1小时",
            "percentage": 0,
            "comment": "来这里玩就是为了这家手办店，人好多，但是手办也很多，确实不便宜的说！最惊艳我的就是这一面墙的蒙奇奇，各不相同，好可爱的说",
            "user_id": 1959997,
            "user_name": "vivian5058",
            "avatar": "https://pic.qyer.com/avatar/001/95/99/97/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 129507,
            "catetypeid": 32,
            "lat": 31.163822,
            "lng": 121.494652,
            "score": 4,
            "image": "https://pic.qyer.com/album/user/863/20/SU9WQBoAYw/index/",
            "cn_name": "世博文化中心",
            "average_hours": "1小时",
            "percentage": 3,
            "comment": "在梅赛德斯奔驰文化中心附近。中国馆很大～",
            "user_id": 5838476,
            "user_name": "SIPO_小胖鱼",
            "avatar": "https://pic.qyer.com/avatar/005/83/84/76/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 1456772,
            "catetypeid": 32,
            "lat": 31.225561,
            "lng": 121.494804,
            "score": 5,
            "cn_name": "上海老街",
            "average_hours": "1小时",
            "percentage": 0,
            "comment": "古香古色的，每个城市都应该有一个这样的地方，让大家拍拍照，开个玩笑，让大家不要遗忘过去。",
            "user_id": 5502874,
            "user_name": "米粒的一家",
            "avatar": "https://pic.qyer.com/avatar/005/50/28/74/120",
            "image": [],
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 129504,
            "catetypeid": 32,
            "lat": 31.235445,
            "lng": 121.473747,
            "score": 4,
            "image": "https://pic.qyer.com/album/user/863/44/SU9WRh4FZg/index/",
            "cn_name": "上海杜莎夫人蜡像馆",
            "average_hours": "1小时",
            "percentage": 31,
            "comment": "国内最早一批蜡像馆，反正我个人不喜欢，慎得慌，但是里面的蜡像非常的逼真，在其他地方、见过",
            "user_id": 5502874,
            "user_name": "米粒的一家",
            "avatar": "https://pic.qyer.com/avatar/005/50/28/74/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 123675,
            "catetypeid": 32,
            "lat": 31.183996,
            "lng": 121.482452,
            "score": 4,
            "cn_name": "文莱馆",
            "en_name": "Brunei Darussalam Pavilion",
            "average_hours": "1小时",
            "percentage": 6,
            "comment": "世博会的一个展馆，个人觉得放到现在也没有什么特别的了，因为有这么多年过去了。",
            "user_id": 5502874,
            "user_name": "米粒的一家",
            "avatar": "https://pic.qyer.com/avatar/005/50/28/74/120",
            "image": [],
            "isrecommend": false,
            "lm": ""
        },
        {
            "id": 1450969,
            "catetypeid": 78,
            "lat": 31.232294,
            "lng": 121.482201,
            "score": 4,
            "cn_name": "德兴馆（广东路）",
            "average_hours": "1小时",
            "percentage": 0,
            "comment": "味道很好，人气很旺，停车需要找地方",
            "user_id": 7515357,
            "user_name": "常棣",
            "avatar": "https://pic.qyer.com/avatar/007/51/53/57/120",
            "image": [],
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 1451343,
            "catetypeid": 78,
            "lat": 31.234564,
            "lng": 121.507439,
            "score": 4,
            "cn_name": "大蔬无界（环球金融中心）",
            "average_hours": "1小时",
            "percentage": 0,
            "comment": "环境很好，就是价格比较贵，适合减肥人士",
            "user_id": 7515357,
            "user_name": "常棣",
            "avatar": "https://pic.qyer.com/avatar/007/51/53/57/120",
            "image": [],
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 1208018,
            "catetypeid": 32,
            "lat": 31.203716,
            "lng": 121.44928,
            "score": 3,
            "cn_name": "朱敏堂宅",
            "average_hours": "1小时",
            "percentage": 0,
            "comment": "只能看看外面，不让进去的啊，很扫兴的说，因为看不出个所以然来。",
            "user_id": 5502874,
            "user_name": "米粒的一家",
            "avatar": "https://pic.qyer.com/avatar/005/50/28/74/120",
            "image": [],
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 1451032,
            "catetypeid": 78,
            "lat": 31.234318,
            "lng": 121.490601,
            "cn_name": "老乾杯",
            "average_hours": "1小时",
            "percentage": 0,
            "image": [],
            "isrecommend": false,
            "en_name": "",
            "score": [],
            "user_id": 0,
            "user_name": "",
            "avatar": "",
            "comment": "",
            "lm": ""
        },
        {
            "id": 1451006,
            "catetypeid": 78,
            "lat": 31.236273,
            "lng": 121.502266,
            "cn_name": "正斗粥面专家（国金中心）",
            "average_hours": "1小时",
            "percentage": 0,
            "image": [],
            "isrecommend": false,
            "en_name": "",
            "score": [],
            "user_id": 0,
            "user_name": "",
            "avatar": "",
            "comment": "",
            "lm": ""
        },
        {
            "id": 1451137,
            "catetypeid": 78,
            "lat": 31.234692,
            "lng": 121.489227,
            "cn_name": "大壶春",
            "average_hours": "1小时",
            "percentage": 0,
            "image": [],
            "isrecommend": false,
            "en_name": "",
            "score": [],
            "user_id": 0,
            "user_name": "",
            "avatar": "",
            "comment": "",
            "lm": ""
        },
        {
            "id": 1464715,
            "catetypeid": 32,
            "lat": 31.211283,
            "lng": 121.452528,
            "cn_name": "黑石公寓",
            "average_hours": "1小时",
            "comment": "喜欢建筑的可以来一观，现在很多艺术类的表演、展览会选址在这里。",
            "user_id": 5502874,
            "user_name": "米粒的一家",
            "avatar": "https://pic.qyer.com/avatar/005/50/28/74/120",
            "image": [],
            "isrecommend": false,
            "en_name": "",
            "score": [],
            "percentage": 0,
            "lm": ""
        },
        {
            "id": 1208036,
            "catetypeid": 32,
            "lat": 31.211767,
            "lng": 121.449776,
            "score": 2,
            "cn_name": "上海滩第一私家花园",
            "average_hours": "1小时",
            "percentage": 0,
            "comment": "不能去看了，就不要当做景点了，去到哪里外面溜达一圈没意思了。",
            "user_id": 5502874,
            "user_name": "米粒的一家",
            "avatar": "https://pic.qyer.com/avatar/005/50/28/74/120",
            "image": [],
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 129525,
            "catetypeid": 32,
            "lat": 31.193027,
            "lng": 121.362595,
            "score": 5,
            "image": "https://pic.qyer.com/album/user/863/20/SU9WQBoBZw/index/",
            "cn_name": "上海动物园",
            "average_hours": "1小时",
            "percentage": 0,
            "comment": "在上海看动物的首选地，里面也有办婚宴的",
            "user_id": 7515357,
            "user_name": "常棣",
            "avatar": "https://pic.qyer.com/avatar/007/51/53/57/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 129515,
            "catetypeid": 32,
            "lat": 30.893976,
            "lng": 121.016922,
            "score": 5,
            "image": "https://pic.qyer.com/album/user/3081/93/QkldQxMEaE4/index/",
            "cn_name": "枫泾",
            "average_hours": "1小时",
            "percentage": 0,
            "comment": "去过很多上海的小镇，感觉枫泾小镇最有味道。门票指的是博物馆，而不是小镇。如果去小镇逛，是不需要门票的。",
            "user_id": 8318690,
            "user_name": "sunrl64",
            "avatar": "https://pic.qyer.com/avatar/008/31/86/90/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 1456771,
            "catetypeid": 32,
            "lat": 31.22724,
            "lng": 121.492096,
            "image": "https://pic.qyer.com/album/user/3353/72/QkpQQR0FZUA/index/",
            "cn_name": "豫园",
            "average_hours": "1小时",
            "percentage": 0,
            "comment": "见识到城隍庙美食广场有多少观光客，就能预计到豫园还有多少立足之地。正因为如此，豫园的旅行价值也打了许多折扣。事实上将豫园与苏州诸园林相比，也未必逊色。江南园林之美，在于体现出中国古典哲学中追求的极致的极致思想---天人合一。",
            "user_id": 4989797,
            "user_name": "DrZou92",
            "avatar": "https://pic.qyer.com/avatar/004/98/97/97/120",
            "isrecommend": false,
            "en_name": "",
            "score": [],
            "lm": ""
        },
        {
            "id": 129523,
            "catetypeid": 32,
            "lat": 31.228331,
            "lng": 121.475525,
            "score": 4,
            "image": "https://pic.qyer.com/album/user/2698/52/Q09cSh8FZEg/index/",
            "cn_name": "上海博物馆",
            "average_hours": "1小时",
            "percentage": 5,
            "comment": "很棒！导读你们可以去借一个，押金100元，让你懂每件物品的来源！（本地人）",
            "user_id": 10395441,
            "user_name": "常胜小子龙",
            "avatar": "https://pic.qyer.com/avatar/010/39/54/41/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 129510,
            "catetypeid": 32,
            "lat": 31.227236,
            "lng": 121.492096,
            "score": 4,
            "image": "https://pic.qyer.com/album/user/314/96/QkhRSxwCZQ/index/",
            "cn_name": "豫园",
            "en_name": "Yu Garden",
            "average_hours": "1小时",
            "percentage": 44,
            "comment": "看着门口很小，没想到里面很大。江南私家园林的特点非常明显，真的是一步一景，布景非常精致，每一样东西的位置都恰到好处！四时花开……明天就过年了 里面有很多的梅花盆景 散发着淡淡的清香……非常推荐游览",
            "user_id": 9861032,
            "user_name": "shoco",
            "avatar": "https://pic.qyer.com/avatar/009/86/10/32/120",
            "isrecommend": false,
            "lm": ""
        },
        {
            "id": 129509,
            "catetypeid": 32,
            "lat": 31.216393,
            "lng": 121.475082,
            "score": 3,
            "image": "https://pic.qyer.com/album/1ac/56/145083/index/",
            "cn_name": "上海新天地",
            "average_hours": "1小时",
            "percentage": 28,
            "comment": "由于很多石库门，法租界的历史外加方便的地理位置，这里是外国人和游客集聚的地方。路上应到英文 西班牙文甚至日文的频率很高。而物价也略贵。至于交通 10、13号线都有地铁。附近也有上海小洋房，外国人很喜欢。推荐来这里看看",
            "user_id": 5838476,
            "user_name": "SIPO_小胖鱼",
            "avatar": "https://pic.qyer.com/avatar/005/83/84/76/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 129514,
            "catetypeid": 32,
            "lat": 31.16003,
            "lng": 121.360115,
            "score": 4,
            "image": "https://pic.qyer.com/album/user/885/15/SUFQQx8HaA/index/",
            "cn_name": "七宝老街",
            "average_hours": "1小时",
            "percentage": 2,
            "comment": "是偶然路过的，古镇比较小 有点江南的感觉 但商业化比较明显……还行吧。我是过年期间去的，好多店铺关门了 ，不过还是很多游客。",
            "user_id": 9861032,
            "user_name": "shoco",
            "avatar": "https://pic.qyer.com/avatar/009/86/10/32/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 129551,
            "catetypeid": 32,
            "lat": 31.117144,
            "lng": 121.019867,
            "cn_name": "东方绿舟",
            "average_hours": "1小时",
            "percentage": 0,
            "image": [],
            "isrecommend": false,
            "en_name": "",
            "score": [],
            "user_id": 0,
            "user_name": "",
            "avatar": "",
            "comment": "",
            "lm": ""
        },
        {
            "id": 129544,
            "catetypeid": 32,
            "lat": 31.321566,
            "lng": 121.554298,
            "score": 4,
            "image": "https://pic.qyer.com/album/user/2765/17/Q05TRxsAZkg/index/",
            "cn_name": "共青森林公园",
            "average_hours": "1小时",
            "percentage": 0,
            "comment": "有烧烤区，适合结伴来烧烤野餐，还有一些游乐设施。",
            "user_id": 1721424,
            "user_name": "anthonybai",
            "avatar": "https://pic.qyer.com/avatar/001/72/14/24/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 129517,
            "catetypeid": 32,
            "lat": 31.060202,
            "lng": 121.727592,
            "score": 5,
            "cn_name": "上海野生动物园",
            "average_hours": "1小时",
            "percentage": 1,
            "comment": "最爱小动物乐园，亲子游玩最合适。",
            "user_id": 9922314,
            "user_name": "Elaine诺宝",
            "avatar": "https://pic.qyer.com/avatar/009/92/23/14/120",
            "image": [],
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 129552,
            "catetypeid": 32,
            "lat": 31.035709,
            "lng": 121.204239,
            "score": 4,
            "image": "https://pic.qyer.com/album/user/2929/81/Q0BXSxIGaUo/index/",
            "cn_name": "泰晤士小镇",
            "average_hours": "1小时",
            "percentage": 4,
            "comment": "哈哈哈，还以为是迪士尼的一个小真呢",
            "user_id": 10395441,
            "user_name": "常胜小子龙",
            "avatar": "https://pic.qyer.com/avatar/010/39/54/41/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        },
        {
            "id": 129519,
            "catetypeid": 32,
            "lat": 31.238157,
            "lng": 121.503662,
            "score": 4,
            "image": "https://pic.qyer.com/album/user/1742/60/QE5RQBwHYE4/index/",
            "cn_name": "陆家嘴",
            "average_hours": "1小时",
            "percentage": 10,
            "comment": "白天路过，晚上来的，本来还想溜溜，奈何一碗咖喱中药味的牛肉汤吃坏了好心情",
            "user_id": 5715741,
            "user_name": "南瓜calla",
            "avatar": "https://pic.qyer.com/avatar/005/71/57/41/120",
            "isrecommend": false,
            "en_name": "",
            "lm": ""
        }
    ]
}