module.exports = {
    "list": [
        {
            "id": 1461340,
            "catetypeid": 148,
            "lat": 31.206367,
            "lng": 121.43914,
            "grade": 0,
            "cn_name": "%Arabica咖啡馆",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FgBzdTZ1I7Cmw/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 1458916,
            "catetypeid": 148,
            "lat": 31.230715,
            "lng": 121.462746,
            "grade": 5,
            "pic": "https://pic.qyer.com/album/user/2806/15/Q0FVRBsCYUA/index/",
            "cn_name": "星巴克臻选·上海烘焙工坊",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FjBz5TbVI-Cmo/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130589,
            "catetypeid": 148,
            "lat": 31.232939,
            "lng": 121.471291,
            "grade": 5,
            "pic": "https://pic.qyer.com/album/user/923/33/SEtWQRkFZQ/index/",
            "cn_name": "大光明电影院(南京西路店)",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTbFI2/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 1459828,
            "catetypeid": 78,
            "lat": 31.216101,
            "lng": 121.453667,
            "grade": 0,
            "pic": "https://pic.qyer.com/album/user/2725/32/Q05XRxkFYk4/index/",
            "cn_name": "皮爷咖啡",
            "en_name": "Peet's Coffee",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FjBz9TbFI9CmQ/",
            "percentage": 0,
            "isrecommend": 0
        },
        {
            "id": 130585,
            "catetypeid": 148,
            "lat": 31.223522,
            "lng": 121.444206,
            "grade": 5,
            "cn_name": "百乐门",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTbFI6/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130625,
            "catetypeid": 148,
            "lat": 31.217913,
            "lng": 121.461426,
            "grade": 2,
            "cn_name": "国泰电影院",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzBTZlI6/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130679,
            "catetypeid": 148,
            "lat": 31.227747,
            "lng": 121.451683,
            "grade": 4.5,
            "pic": "https://pic.qyer.com/album/user/923/22/SEtWQBgDYA/index/",
            "cn_name": "静安体育馆",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzBTY1I2/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130680,
            "catetypeid": 148,
            "lat": 31.226419,
            "lng": 121.504021,
            "grade": 5,
            "pic": "https://pic.qyer.com/album/user/898/86/SUBdShwFaA/index/",
            "cn_name": "上海黄浦江游览",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzBTbFI_/",
            "percentage": 5,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130840,
            "catetypeid": 148,
            "lat": 31.245419,
            "lng": 121.493454,
            "grade": 0,
            "cn_name": "非常时髦酒吧",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBz5TYFI_/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 1147347,
            "catetypeid": 78,
            "lat": 31.218403,
            "lng": 121.458382,
            "grade": 0,
            "cn_name": "Paras Coffee",
            "en_name": "Paras Coffee",
            "poi_url": "//place.qyer.com/poi/V2UJYlFiBzFTZ1I7Cms/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0
        },
        {
            "id": 1147371,
            "catetypeid": 78,
            "lat": 31.248436,
            "lng": 121.449066,
            "grade": 0,
            "cn_name": "undefine",
            "en_name": "undefine",
            "poi_url": "//place.qyer.com/poi/V2UJYlFiBzFTZ1I4Cm0/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0
        },
        {
            "id": 1454071,
            "catetypeid": 78,
            "lat": 31.20569,
            "lng": 121.457893,
            "grade": 0,
            "cn_name": "BREAD etc",
            "en_name": "BREAD etc",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FjBzJTZFI4Cm0/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0
        },
        {
            "id": 1454089,
            "catetypeid": 78,
            "lat": 31.221495,
            "lng": 121.475319,
            "grade": 0,
            "cn_name": "鹰集咖啡（新天地店）",
            "en_name": "S.Engine Coffee",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FjBzJTZFI3CmU/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0
        },
        {
            "id": 1455290,
            "catetypeid": 148,
            "lat": 31.205715,
            "lng": 121.455315,
            "grade": 0,
            "cn_name": "OPS CAFE",
            "en_name": "OPS CAFE",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FjBzNTZlI2Cmw/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0
        },
        {
            "id": 1456572,
            "catetypeid": 148,
            "lat": 31.208075,
            "lng": 121.41777,
            "grade": 0,
            "cn_name": "啤酒阿姨（延安西路店）",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FjBzBTYVI4Cm4/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130548,
            "catetypeid": 148,
            "lat": 31.209219,
            "lng": 121.450348,
            "grade": 0,
            "cn_name": "老麦咖啡馆",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTYFI3/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130549,
            "catetypeid": 148,
            "lat": 31.228273,
            "lng": 121.478935,
            "grade": 5,
            "cn_name": "上海大世界游乐城",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTYFI2/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130584,
            "catetypeid": 148,
            "lat": 31.200184,
            "lng": 121.437111,
            "grade": 4,
            "cn_name": "小小花园",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTbFI7/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130587,
            "catetypeid": 148,
            "lat": 31.231302,
            "lng": 121.470695,
            "grade": 0,
            "cn_name": "上海双年展",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTbFI4/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130672,
            "catetypeid": 148,
            "lat": 31.192539,
            "lng": 121.540665,
            "grade": 0,
            "cn_name": "浦东图书馆",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzBTY1I9/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        }
    ]
}