module.exports = {
    "list": [
        {
            "id": 1461340,
            "catetypeid": 148,
            "lat": 31.206367,
            "lng": 121.43914,
            "grade": 0,
            "cn_name": "%Arabica咖啡馆",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FgBzdTZ1I7Cmw/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 1458916,
            "catetypeid": 148,
            "lat": 31.230715,
            "lng": 121.462746,
            "grade": 5,
            "pic": "https://pic.qyer.com/album/user/2806/15/Q0FVRBsCYUA/index/",
            "cn_name": "星巴克臻选·上海烘焙工坊",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FjBz5TbVI-Cmo/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130605,
            "catetypeid": 78,
            "lat": 31.206099,
            "lng": 121.468376,
            "grade": 4,
            "cn_name": "日月光中心广场",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzBTZFI6/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 1635104,
            "catetypeid": 78,
            "lat": 31.230852,
            "lng": 121.461738,
            "grade": 4.6,
            "cn_name": "星巴克臻选烘焙工坊",
            "poi_url": "//place.qyer.com/poi/V2UJZVFlBzNTZVI_Cmg/",
            "pic": "",
            "isrecommend": 0,
            "en_name": "",
            "percentage": 0
        },
        {
            "id": 131061,
            "catetypeid": 78,
            "lat": 31.223793,
            "lng": 121.447548,
            "grade": 4,
            "pic": "https://pic.qyer.com/album/user/1318/20/QEpUShgHYks/index/",
            "cn_name": "西树泡芙",
            "poi_url": "//place.qyer.com/poi/V2UJYFFnBzZTYlI-/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130577,
            "catetypeid": 78,
            "lat": 31.223877,
            "lng": 121.427681,
            "grade": 3.8,
            "cn_name": "小杨生煎(长宁路店)",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTY1I4/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130510,
            "catetypeid": 78,
            "lat": 31.230963,
            "lng": 121.461021,
            "grade": 3.8,
            "cn_name": "外婆家(南京西路店)",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTZVI_/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130518,
            "catetypeid": 78,
            "lat": 31.226507,
            "lng": 121.491531,
            "grade": 4.5,
            "pic": "https://pic.qyer.com/album/user/1308/34/QEpVShkDYkw/index/",
            "cn_name": "南翔馒头店",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTZVI3/",
            "percentage": 4,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 1635066,
            "catetypeid": 78,
            "lat": 31.220954,
            "lng": 121.475267,
            "grade": 4.1,
            "cn_name": "夜上海",
            "poi_url": "//place.qyer.com/poi/V2UJZVFlBzNTZFI5Cmo/",
            "pic": "",
            "isrecommend": 0,
            "en_name": "",
            "percentage": 0
        },
        {
            "id": 1635087,
            "catetypeid": 78,
            "lat": 31.23179,
            "lng": 121.47174,
            "grade": 5,
            "cn_name": "芭芭露莎",
            "poi_url": "//place.qyer.com/poi/V2UJZVFlBzNTZFI3Cms/",
            "pic": "",
            "isrecommend": 0,
            "en_name": "",
            "percentage": 0
        },
        {
            "id": 1635754,
            "catetypeid": 78,
            "lat": 31.2353,
            "lng": 121.48398,
            "grade": 4.5,
            "cn_name": "THE PRESS",
            "poi_url": "//place.qyer.com/poi/V2UJZVFlBzNTY1I6Cmg/",
            "pic": "",
            "isrecommend": 0,
            "en_name": "",
            "percentage": 0
        },
        {
            "id": 1636886,
            "catetypeid": 78,
            "lat": 31.238982,
            "lng": 121.489456,
            "grade": 4.8,
            "cn_name": "和平饭店Cathay Room华懋阁",
            "poi_url": "//place.qyer.com/poi/V2UJZVFlBzBTbFI3Cmo/",
            "pic": "",
            "isrecommend": 0,
            "en_name": "",
            "percentage": 0
        },
        {
            "id": 130579,
            "catetypeid": 78,
            "lat": 31.205631,
            "lng": 121.467873,
            "grade": 4,
            "cn_name": "满记甜品(日月光店)",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTY1I2/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130716,
            "catetypeid": 78,
            "lat": 31.227674,
            "lng": 121.480835,
            "grade": 2.7,
            "pic": "https://pic.qyer.com/album/user/1642/73/QE9RQB0EYkE/index/",
            "cn_name": "阿姨奶茶专卖",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzFTZVI5/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 1459828,
            "catetypeid": 78,
            "lat": 31.216101,
            "lng": 121.453667,
            "grade": 0,
            "pic": "https://pic.qyer.com/album/user/2725/32/Q05XRxkFYk4/index/",
            "cn_name": "皮爷咖啡",
            "en_name": "Peet's Coffee",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FjBz9TbFI9CmQ/",
            "percentage": 0,
            "isrecommend": 0
        },
        {
            "id": 1635316,
            "catetypeid": 78,
            "lat": 31.203317,
            "lng": 121.451945,
            "grade": 4.5,
            "cn_name": "le Comptoir de Pierre Gagnaire(建业里嘉佩乐酒店)",
            "poi_url": "//place.qyer.com/poi/V2UJZVFlBzNTZ1I-Cmo/",
            "pic": "",
            "isrecommend": 0,
            "en_name": "",
            "percentage": 0
        },
        {
            "id": 130506,
            "catetypeid": 78,
            "lat": 31.229195,
            "lng": 121.459229,
            "grade": 4.5,
            "pic": "https://pic.qyer.com/album/user/2486/85/Q01dRBICY0k/index/",
            "cn_name": "小杨生煎(吴江路店)",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTZFI5/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130513,
            "catetypeid": 78,
            "lat": 31.234552,
            "lng": 121.470604,
            "grade": 5,
            "cn_name": "小杨生煎(黄河路店)",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTZVI8/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130569,
            "catetypeid": 78,
            "lat": 31.240004,
            "lng": 121.436745,
            "grade": 5,
            "pic": "https://pic.qyer.com/album/user/1318/24/QEpUShgDaU0/index/",
            "cn_name": "海底捞火锅店(长寿路店)",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTYlI2/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130641,
            "catetypeid": 78,
            "lat": 31.220528,
            "lng": 121.467567,
            "grade": 5,
            "pic": "https://pic.qyer.com/album/user/2577/73/Q0xSRR0EY0o/index/",
            "cn_name": "光明邨大酒家(淮海中路总店)",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzBTYFI-/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        }
    ]
}