module.exports = {
    "list": [
        {
            "id": 1456738,
            "catetypeid": 32,
            "lat": 31.240261,
            "lng": 121.490578,
            "grade": 5,
            "pic": "https://pic.qyer.com/album/user/3098/35/QklcShkCZ0E/index/",
            "cn_name": "上海外滩",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FjBzBTY1I8CmQ/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 1456801,
            "catetypeid": 32,
            "lat": 31.23472,
            "lng": 121.474899,
            "grade": 4.8,
            "pic": "https://pic.qyer.com/album/user/3035/37/QklWRxkAZEA/index/",
            "cn_name": "南京路步行街",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FjBzBTbFI_Cm0/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 1456802,
            "catetypeid": 32,
            "lat": 31.239689,
            "lng": 121.499756,
            "grade": 5,
            "pic": "https://pic.qyer.com/album/user/3302/79/QkpVQB0OY04/index/",
            "cn_name": "东方明珠",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FjBzBTbFI_Cm4/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 1456741,
            "catetypeid": 32,
            "lat": 31.225719,
            "lng": 121.492592,
            "grade": 5,
            "pic": "https://pic.qyer.com/album/user/3338/88/QkpWShIPaU8/index/",
            "cn_name": "上海城隍庙",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FjBzBTY1I7Cm0/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 1456771,
            "catetypeid": 32,
            "lat": 31.22724,
            "lng": 121.492096,
            "grade": 0,
            "pic": "https://pic.qyer.com/album/user/3353/72/QkpQQR0FZUA/index/",
            "cn_name": "豫园",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FjBzBTY1I4Cm0/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 129501,
            "catetypeid": 32,
            "lat": 31.240891,
            "lng": 121.490189,
            "grade": 4.7,
            "pic": "https://pic.qyer.com/album/user/1831/1/QEFWQxoGZ0s/index/",
            "cn_name": "外滩",
            "poi_url": "//place.qyer.com/poi/V2UJYVFvBzNTZFI-/",
            "percentage": 61,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 129504,
            "catetypeid": 32,
            "lat": 31.235445,
            "lng": 121.473747,
            "grade": 4.1,
            "pic": "https://pic.qyer.com/album/user/863/44/SU9WRh4FZg/index/",
            "cn_name": "上海杜莎夫人蜡像馆",
            "poi_url": "//place.qyer.com/poi/V2UJYVFvBzNTZFI7/",
            "percentage": 31,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 129519,
            "catetypeid": 32,
            "lat": 31.238157,
            "lng": 121.503662,
            "grade": 4.5,
            "pic": "https://pic.qyer.com/album/user/1742/60/QE5RQBwHYE4/index/",
            "cn_name": "陆家嘴",
            "poi_url": "//place.qyer.com/poi/V2UJYVFvBzNTZVI2/",
            "percentage": 10,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 129509,
            "catetypeid": 32,
            "lat": 31.216393,
            "lng": 121.475082,
            "grade": 3.9,
            "pic": "https://pic.qyer.com/album/1ac/56/145083/index/",
            "cn_name": "上海新天地",
            "poi_url": "//place.qyer.com/poi/V2UJYVFvBzNTZFI2/",
            "percentage": 28,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 129502,
            "catetypeid": 32,
            "lat": 31.208599,
            "lng": 121.468781,
            "grade": 3.9,
            "pic": "https://pic.qyer.com/album/user/1767/39/QE5TRRkOZE0/index/",
            "cn_name": "田子坊",
            "poi_url": "//place.qyer.com/poi/V2UJYVFvBzNTZFI9/",
            "percentage": 43,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 129510,
            "catetypeid": 32,
            "lat": 31.227236,
            "lng": 121.492096,
            "grade": 4.3,
            "pic": "https://pic.qyer.com/album/user/314/96/QkhRSxwCZQ/index/",
            "cn_name": "豫园",
            "en_name": "Yu Garden",
            "poi_url": "//place.qyer.com/poi/V2UJYVFvBzNTZVI_/",
            "percentage": 44,
            "isrecommend": 0
        },
        {
            "id": 1456772,
            "catetypeid": 32,
            "lat": 31.225561,
            "lng": 121.494804,
            "grade": 5,
            "cn_name": "上海老街",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FjBzBTY1I4Cm4/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 129500,
            "catetypeid": 32,
            "lat": 31.239689,
            "lng": 121.499756,
            "grade": 4.4,
            "pic": "https://pic.qyer.com/album/user/863/19/SU9WQxMDYQ/index/",
            "cn_name": "东方明珠电视塔",
            "poi_url": "//place.qyer.com/poi/V2UJYVFvBzNTZFI_/",
            "percentage": 46,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 129834,
            "catetypeid": 32,
            "lat": 31.210329,
            "lng": 121.444283,
            "grade": 4.5,
            "pic": "https://pic.qyer.com/album/user/2694/60/Q09cRhwHZUs/index/",
            "cn_name": "武康路",
            "poi_url": "//place.qyer.com/poi/V2UJYVFvBz5TZ1I7/",
            "percentage": 9,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 129612,
            "catetypeid": 32,
            "lat": 31.225748,
            "lng": 121.492538,
            "grade": 4.1,
            "pic": "https://pic.qyer.com/album/user/1831/1/QEFWQxoGaE4/index/",
            "cn_name": "上海老城隍庙",
            "poi_url": "//place.qyer.com/poi/V2UJYVFvBzBTZVI9/",
            "percentage": 46,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 129560,
            "catetypeid": 32,
            "lat": 31.259939,
            "lng": 121.49852,
            "grade": 4.4,
            "pic": "https://pic.qyer.com/album/user/923/14/SEtWQx4CaQ/index/",
            "cn_name": "1933老场坊",
            "poi_url": "//place.qyer.com/poi/V2UJYVFvBzNTYlI_/",
            "percentage": 12,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 129523,
            "catetypeid": 32,
            "lat": 31.228331,
            "lng": 121.475525,
            "grade": 4.3,
            "pic": "https://pic.qyer.com/album/user/2698/52/Q09cSh8FZEg/index/",
            "cn_name": "上海博物馆",
            "poi_url": "//place.qyer.com/poi/V2UJYVFvBzNTZlI8/",
            "percentage": 5,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 129533,
            "catetypeid": 32,
            "lat": 31.288675,
            "lng": 121.507103,
            "grade": 4,
            "pic": "https://pic.qyer.com/album/user/923/19/SEtWQxMDYw/index/",
            "cn_name": "同济大学",
            "poi_url": "//place.qyer.com/poi/V2UJYVFvBzNTZ1I8/",
            "percentage": 3,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 129505,
            "catetypeid": 32,
            "lat": 31.240768,
            "lng": 121.481796,
            "grade": 4.4,
            "pic": "https://pic.qyer.com/album/168/58/145071/index/",
            "cn_name": "南京路",
            "poi_url": "//place.qyer.com/poi/V2UJYVFvBzNTZFI6/",
            "percentage": 22,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 129586,
            "catetypeid": 32,
            "lat": 31.24968,
            "lng": 121.496979,
            "grade": 4.5,
            "pic": "https://pic.qyer.com/album/user/2951/8/Q0BQQxoPZk0/index/",
            "cn_name": "外白渡桥",
            "poi_url": "//place.qyer.com/poi/V2UJYVFvBzNTbFI5/",
            "percentage": 39,
            "isrecommend": 0,
            "en_name": ""
        }
    ]
}