module.exports = {
    "list": [
        {
            "id": 1538886,
            "catetypeid": 147,
            "lat": 31.243059,
            "lng": 121.472443,
            "grade": 4.4,
            "cn_name": "上海大悦城",
            "poi_url": "//place.qyer.com/poi/V2UJZlFlBz5TbFI3Cmo/",
            "pic": "",
            "isrecommend": 0,
            "en_name": "",
            "percentage": 0
        },
        {
            "id": 1464824,
            "catetypeid": 32,
            "lat": 31.210124,
            "lng": 121.427009,
            "grade": 5,
            "cn_name": "上生新所",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FgBzJTbFI9Cmg/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 1539027,
            "catetypeid": 147,
            "lat": 31.234565,
            "lng": 121.507439,
            "grade": 0,
            "cn_name": "上海环球金融中心",
            "poi_url": "//place.qyer.com/poi/V2UJZlFlBz9TZFI9Cms/",
            "pic": "",
            "isrecommend": 0,
            "en_name": "",
            "percentage": 0
        },
        {
            "id": 130527,
            "catetypeid": 147,
            "lat": 31.194576,
            "lng": 121.437523,
            "grade": 4.5,
            "pic": "https://pic.qyer.com/album/user/2094/11/Q0lcRhsGZEs/index/",
            "cn_name": "徐家汇",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTZlI4/",
            "percentage": 4,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130669,
            "catetypeid": 147,
            "lat": 31.223797,
            "lng": 121.450455,
            "grade": 0,
            "cn_name": "静安嘉里中心",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzBTYlI2/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130557,
            "catetypeid": 147,
            "lat": 31.218603,
            "lng": 121.475075,
            "grade": 4,
            "pic": "https://pic.qyer.com/album/user/1558/84/QExQShIDZ0A/index/",
            "cn_name": "新天地广场",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTYVI4/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130531,
            "catetypeid": 147,
            "lat": 31.242668,
            "lng": 121.471817,
            "grade": 4,
            "pic": "https://pic.qyer.com/album/user/2831/31/Q0FWQxkGaEk/index/",
            "cn_name": "上海大悦城",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTZ1I-/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130551,
            "catetypeid": 147,
            "lat": 31.193293,
            "lng": 121.439583,
            "grade": 4,
            "cn_name": "美罗城",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTYVI-/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 1451429,
            "catetypeid": 147,
            "lat": 31.218794,
            "lng": 121.451469,
            "grade": 0,
            "cn_name": "日常 ",
            "en_name": "Nichijo",
            "poi_url": "//place.qyer.com/poi/V2UJZ1FjBzdTYFI9CmU/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0
        },
        {
            "id": 1538905,
            "catetypeid": 147,
            "lat": 31.21553,
            "lng": 121.458339,
            "grade": 4.5,
            "cn_name": "环贸iapm商场",
            "poi_url": "//place.qyer.com/poi/V2UJZlFlBz5TbVI_Cmk/",
            "pic": "",
            "isrecommend": 0,
            "en_name": "",
            "percentage": 0
        },
        {
            "id": 130528,
            "catetypeid": 147,
            "lat": 31.194443,
            "lng": 121.437241,
            "grade": 4.5,
            "cn_name": "港汇恒隆广场",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTZlI3/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130530,
            "catetypeid": 147,
            "lat": 31.208748,
            "lng": 121.468925,
            "grade": 4.2,
            "cn_name": "气味图书馆(田子坊店)",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTZ1I_/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130559,
            "catetypeid": 147,
            "lat": 31.259863,
            "lng": 121.463661,
            "grade": 4.5,
            "pic": "https://pic.qyer.com/album/user/2710/67/Q05UQhwAZ08/index/",
            "cn_name": "月星·环球港",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTYVI2/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130564,
            "catetypeid": 147,
            "lat": 31.234858,
            "lng": 121.474869,
            "grade": 3,
            "cn_name": "第一百货(南京东路店)",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTYlI7/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130818,
            "catetypeid": 147,
            "lat": 31.185949,
            "lng": 121.442673,
            "grade": 4,
            "cn_name": "星游城",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBz5TZVI3/",
            "percentage": 0,
            "pic": "",
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 130534,
            "catetypeid": 147,
            "lat": 31.232092,
            "lng": 121.476402,
            "grade": 4,
            "pic": "https://pic.qyer.com/album/129/76/145040/index/",
            "cn_name": "上海来福士广场",
            "poi_url": "//place.qyer.com/poi/V2UJYFFmBzNTZ1I7/",
            "percentage": 0,
            "isrecommend": 0,
            "en_name": ""
        },
        {
            "id": 1538885,
            "catetypeid": 147,
            "lat": 31.233251,
            "lng": 121.412548,
            "grade": 4.8,
            "cn_name": "月星环球港",
            "poi_url": "//place.qyer.com/poi/V2UJZlFlBz5TbFI3Cmk/",
            "pic": "",
            "isrecommend": 0,
            "en_name": "",
            "percentage": 0
        },
        {
            "id": 1538892,
            "catetypeid": 147,
            "lat": 31.238253,
            "lng": 121.499627,
            "grade": 4.5,
            "pic": "https://pic.qyer.com/album/user/3359/5/QkpQSxoCYEs/index/",
            "cn_name": "上海迪士尼旗舰店（陆家嘴店）",
            "poi_url": "//place.qyer.com/poi/V2UJZlFlBz5TbFI2Cm4/",
            "isrecommend": 0,
            "en_name": "",
            "percentage": 0
        },
        {
            "id": 1538926,
            "catetypeid": 147,
            "lat": 31.223097,
            "lng": 121.447514,
            "grade": 4.4,
            "cn_name": "芮欧百货",
            "poi_url": "//place.qyer.com/poi/V2UJZlFlBz5TbVI9Cmo/",
            "pic": "",
            "isrecommend": 0,
            "en_name": "",
            "percentage": 0
        },
        {
            "id": 1539001,
            "catetypeid": 147,
            "lat": 31.238387,
            "lng": 121.485476,
            "grade": 0,
            "cn_name": "新世界大丸百货",
            "poi_url": "//place.qyer.com/poi/V2UJZlFlBz9TZFI_Cm0/",
            "pic": "",
            "isrecommend": 0,
            "en_name": "",
            "percentage": 0
        }
    ]
}